import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  // Dry food
  {
    id: "junior_chicken",
    name: "ONE Mini Junior \u2013 Pollo",
    nameEn: "ONE Mini Junior \u2013 Chicken",
    type: "dry",
    desc: "Ricco in Pollo con Riso. Sostiene una crescita sana e difese naturali forti grazie agli antiossidanti.",
    descEn: "Rich in Chicken with Rice. Supports healthy growth and strong natural defenses with antioxidants.",
    img: "/images/secco_junior.jpg",
    price: 6.50,
    criteria: { lifestage: "Junior", health: ["Nessuno", "Digestione sensibile"] },
    pairing: "adult_wet",
  },
  {
    id: "senior_chicken",
    name: "ONE Mini Senior 8+ \u2013 Pollo",
    nameEn: "ONE Mini Senior 8+ \u2013 Chicken",
    type: "dry",
    desc: "Ricco in Pollo. Formulato per cani di piccola taglia oltre gli 8 anni per la funzione cardiaca.",
    descEn: "Rich in Chicken. Formulated for small dogs over 8 years for cardiac function.",
    img: "/images/secco_senior.jpg",
    price: 6.50,
    criteria: { lifestage: "Senior", health: ["Nessuno", "Controllo del peso"] },
    pairing: "senior_wet",
  },
  {
    id: "active_chicken",
    name: "ONE Mini Active \u2013 Pollo",
    nameEn: "ONE Mini Active \u2013 Chicken",
    type: "dry",
    desc: "Ricco in Pollo con Riso. Profilo energetico elevato per sostenere i cani molto attivi.",
    descEn: "Rich in Chicken with Rice. High energy profile to support very active dogs.",
    img: "/images/secco_active.jpg",
    price: 6.50,
    criteria: { lifestage: "Adult", activity: ["Attivo", "Molto Attivo"], health: ["Nessuno"] },
    pairing: "active_wet",
  },
  {
    id: "adult_beef",
    name: "ONE Mini Adult \u2013 Manzo",
    nameEn: "ONE Mini Adult \u2013 Beef",
    type: "dry",
    desc: "Ricco in Manzo con Riso. Nutrizione avanzata per un microbioma sano e difese naturali.",
    descEn: "Rich in Beef with Rice. Advanced nutrition for a healthy microbiome and natural defenses.",
    img: "/images/secco_adult_manzo.jpg",
    price: 5.90,
    criteria: { lifestage: "Adult", activity: ["Normale", "Sedentario"], health: ["Nessuno", "Appetito difficile"] },
    pairing: "adult_wet",
  },
  {
    id: "weight_turkey",
    name: "ONE Mini Weight Control \u2013 Tacchino",
    nameEn: "ONE Mini Weight Control \u2013 Turkey",
    type: "dry",
    desc: "Ricco in Tacchino. Contiene il 40% di grassi in meno rispetto alla formula Adult.",
    descEn: "Rich in Turkey. Contains 40% less fat compared to the Adult formula.",
    img: "/images/secco_weight.jpg",
    price: 6.90,
    criteria: { lifestage: "Adult", health: ["Controllo del peso"] },
    pairing: "weight_wet",
  },
  {
    id: "delicate_salmon",
    name: "ONE Mini Delicate \u2013 Salmone",
    nameEn: "ONE Mini Delicate \u2013 Salmon",
    type: "dry",
    desc: "Ricco in Salmone con Riso. Progettato con Omega 3 per pelli sensibili e alta digeribilit\u00e0.",
    descEn: "Rich in Salmon with Rice. Designed with Omega 3 for sensitive skin and high digestibility.",
    img: "/images/secco_delicate.jpg",
    price: 6.90,
    criteria: { lifestage: "Adult", health: ["Pelle & Pelo", "Digestione sensibile"] },
    pairing: "delicate_wet",
  },
  {
    id: "monoprotein_turkey",
    name: "ONE Mini Monoprotein \u2013 Tacchino",
    nameEn: "ONE Mini Monoprotein \u2013 Turkey",
    type: "dry",
    desc: "Senza cereali, unica fonte di proteine animali per ridurre i rischi di intolleranze.",
    descEn: "Grain-free, single animal protein source to reduce intolerance risks.",
    img: "/images/secco_monoprotein.jpg",
    price: 7.50,
    criteria: { lifestage: "Adult", health: ["Intolleranze"] },
    pairing: "delicate_wet",
  },
  // Wet food
  {
    id: "active_wet",
    name: "Active Filetti",
    nameEn: "Active Fillets",
    type: "wet",
    desc: "Teneri filetti in salsa, ideali per supportare il metabolismo energetico.",
    descEn: "Tender fillets in sauce, ideal for supporting energy metabolism.",
    img: "/images/umido_active.jpg",
    price: 3.50,
  },
  {
    id: "adult_wet",
    name: "Adult Umido Mix",
    nameEn: "Adult Wet Mix",
    type: "wet",
    desc: "Bocconcini in salsa altamente digeribili. Un pasto delizioso e bilanciato.",
    descEn: "Highly digestible chunks in sauce. A delicious and balanced meal.",
    img: "/images/umido_adult.jpg",
    price: 3.50,
  },
  {
    id: "weight_wet",
    name: "Weight Control Umido",
    nameEn: "Weight Control Wet",
    type: "wet",
    desc: "Ricetta gustosa ma povera di grassi, studiata per il peso forma.",
    descEn: "Tasty but low-fat recipe, designed for ideal weight.",
    img: "/images/umido_weight.jpg",
    price: 3.50,
  },
  {
    id: "delicate_wet",
    name: "Delicate Salmone Umido",
    nameEn: "Delicate Salmon Wet",
    type: "wet",
    desc: "Senza grano aggiunto, formulato per la salute della pelle e del pelo.",
    descEn: "No added wheat, formulated for skin and coat health.",
    img: "/images/umido_delicate.jpg",
    price: 3.50,
  },
  {
    id: "senior_wet",
    name: "Senior Soft Umido",
    nameEn: "Senior Soft Wet",
    type: "wet",
    desc: "Bocconcini pi\u00f9 morbidi, arricchiti per supportare le articolazioni.",
    descEn: "Softer chunks, enriched to support joints.",
    img: "/images/umido_senior.jpg",
    price: 3.50,
  },
  // Care & Snacks
  {
    id: "dentalife_small",
    name: "DentaLife Small 7-12kg",
    nameEn: "DentaLife Small 7-12kg",
    type: "care",
    desc: "Purifica l'alito e previene la formazione del tartaro. Pack mensile.",
    descEn: "Purifies breath and prevents tartar buildup. Monthly pack.",
    img: "/images/dentalife.jpg",
    price: 2.50,
  },
  {
    id: "adventuros_nuggets",
    name: "Adventuros Nuggets",
    nameEn: "Adventuros Nuggets",
    type: "snack",
    desc: "Snack premio ricco in cinghiale. Perfetto per l'addestramento.",
    descEn: "Reward snack rich in wild boar. Perfect for training.",
    img: "/images/adventuros.jpg",
    price: 2.90,
  },
];

export const PRODUCTS_MAP: Record<string, Product> = Object.fromEntries(
  PRODUCTS.map((p) => [p.id, p])
);
